name: asset_price_simulator
description: A pure Dart package for simulating realistic crypto and stock price movements with natural-looking price data.
version: 0.1.0
repository: https://github.com/elmissouri16/asset_price_simulator

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
